CREATE TABLE [User] (
    Uid UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    Email NVARCHAR(320) NOT NULL,
    Username NVARCHAR(16) NOT NULL,
    AmaxUsername NVARCHAR(16),
    PasswordHash VARCHAR(60) NOT NULL
);

CREATE TABLE PlayerStatsSnapshot (
    SnapshotId UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    TotalFans INT NOT NULL,
    TotalRaceTimeMilleconds BIGINT NOT NULL,
    DriverScore INT NOT NULL,
    RaceStarts INT NOT NULL,
    RaceWins INT NOT NULL,
    RacePodiums INT NOT NULL,
    PowerUpUses INT NOT NULL,
    PowerUpHits INT NOT NULL,
    Date DATETIME NOT NULL
);

CREATE TABLE Session (
    SessionId UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    Uid UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES [User](Uid),
    Name NVARCHAR(16) NOT NULL,
    StartSnapshotID UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES PlayerStatsSnapshot(SnapshotId),
    EndSnapshotID UNIQUEIDENTIFIER FOREIGN KEY REFERENCES PlayerStatsSnapshot(SnapshotId)
);

CREATE TABLE Mod (
    ModId UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    Uid UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES [User](Uid),
    Title NVARCHAR(32) NOT NULL,
    Type VARCHAR(16) NOT NULL,
    Description NVARCHAR(128) NOT NULL,
    UploadDate DATE NOT NULL,
    EditDate DATE NOT NULL,
    FilePath NVARCHAR(64) NOT NULL
);

CREATE TABLE PreviewImage (
    ImageId UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    ModId UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES Mod(ModId),
    FilePath NVARCHAR(64) NOT NULL
);