CREATE TABLE FavouriteMod (
    FavouriteId UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    Uid UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES [User](Uid),
    ModId UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES Mod(ModId)
);