name: .NET

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x
    
    - name: Restore dependencies
      run: dotnet restore backend/racebookApi/racebookApi.csproj
    
    - name: Build
      run: dotnet build --no-restore backend/racebookApi/racebookApi.csproj
    
    - name: Restore test dependencies
      run: dotnet restore backend/racebookApiTests/racebookApiTests.csproj
    
    - name: Build tests
      run: dotnet build --no-restore backend/racebookApiTests/racebookApiTests.csproj
    
    - name: Test
      run: dotnet test --no-build --verbosity normal backend/racebookApiTests/racebookApiTests.csproj